// German names for the polities that appear in the border snapshots.
//
// The source dataset is English-only, and the whole app is German-first, so the
// names are translated once at build time. 72 names cover every snapshot in the
// biblical span; anything new falls through to the English original, which is
// visible in the review output of scripts/build-borders.mjs.
export const POLITIES_DE = {
  'Achaemenid Empire': 'Achämenidenreich',
  Arabs: 'Araber',
  Arameans: 'Aramäer',
  Armenia: 'Armenien',
  Assyria: 'Assyrien',
  Atropatene: 'Atropatene',
  Axum: 'Aksum',
  Babylonia: 'Babylonien',
  Bactria: 'Baktrien',
  Bithynia: 'Bithynien',
  'Bosporan Kingdom': 'Bosporanisches Reich',
  'Bosporian Kingdom': 'Bosporanisches Reich',
  Canaan: 'Kanaan',
  Cappadocia: 'Kappadokien',
  Carthage: 'Karthago',
  'Carthaginian Empire': 'Karthagisches Reich',
  Colchis: 'Kolchis',
  Crete: 'Kreta',
  Cycladic: 'Kykladen',
  Daces: 'Daker',
  Dacia: 'Dakien',
  Damot: 'Damot',
  Dardania: 'Dardanien',
  Egypt: 'Ägypten',
  Elam: 'Elam',
  'Empire of Alexander': 'Reich Alexanders des Großen',
  Etrurians: 'Etrusker',
  'Greek city-states': 'Griechische Stadtstaaten',
  'Greek colonies': 'Griechische Kolonien',
  Hadramaut: 'Hadramaut',
  'Himyarite Kingdom': 'Himjar',
  Hittites: 'Hethiter',
  'Hurrian Kingdoms': 'Hurritische Reiche',
  Illyrians: 'Illyrer',
  Judea: 'Judäa',
  Kerma: 'Kerma',
  'Kingdom of Antigonus': 'Reich des Antigonos',
  'Kingdom of David and Solomon': 'Reich Davids und Salomos',
  'Kingdom of Gala': 'Reich des Gala',
  'Kingdom of Kassander': 'Reich des Kassander',
  'Kingdom of Lysimachus': 'Reich des Lysimachos',
  Kush: 'Kusch',
  'Kushan Empire': 'Kuschanreich',
  Maan: "Ma'in",
  'Macedon and Hellenic League': 'Makedonien und Hellenischer Bund',
  Mascat: 'Maskat',
  Meroe: 'Meroë',
  Minoan: 'Minoische Kultur',
  'Nabatean Kingdom': 'Nabatäerreich',
  Numidia: 'Numidien',
  'Odrysian Kingdom': 'Odrysenreich',
  Parthia: 'Parthien',
  'Parthian Empire': 'Partherreich',
  Pergamon: 'Pergamon',
  Phrygians: 'Phryger',
  'Ptolemaic Kingdom': 'Ptolemäerreich',
  Qataban: 'Qataban',
  'Roman Empire': 'Römisches Reich',
  'Roman Republic': 'Römische Republik',
  Rome: 'Rom',
  Saba: 'Saba',
  Sabines: 'Sabiner',
  Sabini: 'Sabiner',
  Samnites: 'Samniten',
  'Seleucid Kingdom': 'Seleukidenreich',
  'Suren Kingdom': 'Suren-Reich',
  Thrace: 'Thrakien',
  Ur: 'Ur',
  Urartu: 'Urartu',
  'city-states': 'Stadtstaaten',
  'minor states': 'Kleinstaaten',
  'state societies and Aramaean kingdoms': 'Aramäische Kleinkönigreiche',
  // corrections (see build-borders.mjs)
  'Israel and Judah': 'Israel und Juda',
};
